### ISSUE TITLE
Issue with @Body of post

### ISSUE THREAD

**Issue by harddownloader** [instantcommerce/next-api-decorators#636]
Hello!

Great idea for a library, I really like it.
But I noticed one problem with me, it is very similar to some kind of bug.

When I add Body my request fails.

![image](https://github.com/instantcommerce/next-api-decorators/assets/55257833/cd79c1a0-8275-4d7b-af0f-ef742a7d384b)

![image](https://github.com/instantcommerce/next-api-decorators/assets/55257833/d20f4572-9f7a-460a-af81-da27312c24fe)

`
import { Body, createHandler, Get, NotFoundException, Post, ValidationPipe } from 'next-api-decorators'
import { IsEmail, IsNotEmpty, IsString, MinLength } from "class-validator"

class LoginDTO {
  @IsEmail()
  @IsString()
  @IsNotEmpty()
  readonly email!: string

  @IsString()
  @IsNotEmpty()
  @MinLength(8)
  readonly password!: string
}

class LoginHandler {

  @Post()
  public async login(@Body() body: LoginDTO) {
    logger.info('Hello World!')
    console.log(123)
    return 'login'
  }
}

export default createHandler(LoginHandler)
`

**Comment by harddownloader** [comment]
P.S.
my package.json
``` json
{
  "name": "app",
  "version": "0.1.0",
  "author": "",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",
    "@mui/icons-material": "^5.11.0",
    "@mui/lab": "^5.0.0-alpha.117",
    "@mui/material": "^5.11.6",
    "@mui/x-date-pickers": "^5.0.16",
    "@next/font": "13.1.6",
    "@sentry/nextjs": "^7.43.0",
    "@tabler/icons-react": "^2.2.0",
    "@types/node": "18.11.18",
    "@types/react": "18.0.27",
    "@types/react-dom": "18.0.10",
    "apexcharts": "^3.37.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "clsx": "^1.2.1",
    "compressorjs": "^1.1.1",
    "eslint": "8.33.0",
    "eslint-config-next": "13.1.6",
    "firebase": "^9.16.0",
    "firebase-admin": "^11.5.0",
    "framer-motion": "^9.0.1",
    "ioredis": "^5.3.2",
    "material-ui-popup-state": "^5.0.4",
    "mobx": "^6.7.0",
    "mobx-react-lite": "^3.4.0",
    "next": "13.1.6",
    "next-api-decorators": "^2.0.2",
    "nookies": "^2.5.2",
    "pino": "^8.15.0",
    "react": "18.2.0",
    "react-apexcharts": "^1.4.0",
    "react-dom": "18.2.0",
    "react-dropzone": "^14.2.3",
    "react-hook-form": "^7.43.0",
    "react-phone-number-input": "^3.2.23",
    "sass": "^1.57.1",
    "sharp": "^0.31.3",
    "socket.io": "^4.6.0",
    "socket.io-client": "^4.6.0",
    "typescript": "4.9.4",
    "uuid": "^9.0.0"
  },
  "devDependencies": {
    "@svgr/webpack": "^6.5.1",
    "@types/uuid": "^9.0.1",
    "autoprefixer": "^10.4.13",
    "postcss": "^8.4.21",
    "tailwindcss": "^3.2.4"
  }
}

```

**Comment by harddownloader** [comment]
P.S.
Response (Error message):

``` json
{
    "statusCode": 500,
    "message": "An unknown error occurred.",
    "errors": [
        "An unknown error occurred."
    ],
    "stack": "TypeError: Cannot read properties of undefined (reading 'length')\n    at D:\\ASG_personal_account\\asg_personal_account_front\\node_modules\\next-api-decorators\\dist\\internals\\handler.js:45:50\n    at Array.map (<anonymous>)\n    at LoginHandler.runMainLayer (D:\\ASG_personal_account\\asg_personal_account_front\\node_modules\\next-api-decorators\\dist\\internals\\handler.js:41:62)\n    at descriptor.value (D:\\ASG_personal_account\\asg_personal_account_front\\node_modules\\next-api-decorators\\dist\\internals\\handler.js:105:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async D:\\ASG_personal_account\\asg_personal_account_front\\node_modules\\@sentry\\nextjs\\cjs\\server\\wrapApiHandlerWithSentry.js:144:33"
}
```

**Comment by harddownloader** [comment]
As I see, it looks like this issue - https://github.com/instantcommerce/next-api-decorators/issues/320

**Comment by harddownloader** [comment]
I re-read the documentation and the similar issue:
https://next-api-decorators.vercel.app/docs/#using-with-swc
https://github.com/instantcommerce/next-api-decorators/issues/320

so since I use NextJS with SWC. I set "experimentalDecorators" and "emitDecoratorMetadata" in my tsconfig as `true`, but it doesn't give the expected results.

![image](https://github.com/instantcommerce/next-api-decorators/assets/55257833/d6d55773-4be7-463d-b46e-b180db3ff652)

tsconfig.json
``` json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

next.config.js
``` javascript
/** @type {import('next').NextConfig} */
const path = require('path')

// This file sets a custom webpack configuration to use your Next.js app
// with Sentry.
// https://nextjs.org/docs/api-reference/next.config.js/introduction
// https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/
const { withSentryConfig } = require('@sentry/nextjs');

const apiURL = new URL(process.env.NEXT_PUBLIC_API_URI)
const allowedImageDomains = process.env.NEXT_PUBLIC_ALLOWED_IMAGE_DOMAINS
  ? process.env.NEXT_PUBLIC_ALLOWED_IMAGE_DOMAINS.split(",")
  : []
const imageConversionFormats = process.env.NEXT_PUBLIC_IMAGE_CONVERSION_FORMATS
  ? process.env.NEXT_PUBLIC_IMAGE_CONVERSION_FORMATS.split(",")
  : []

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: [apiURL.hostname, ...allowedImageDomains],
    formats: imageConversionFormats,
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    dangerouslyAllowSVG: true,
  },
  sassOptions: {
    includePaths: [path.join(__dirname, 'styles')],
  },
  webpack(config, { isServer }) {
    config.module.rules.push({
      test: /\.svg$/i,
      issuer: /\.[jt]sx?$/,
      use: ['@svgr/webpack'],
    })

    if (!isServer) {
      // don't resolve 'fs' module on the client to prevent this error on build --> Error: Can't resolve 'fs'
      config.resolve.fallback = {
        fs: false
      }
    }

    return config
  },
}

module.exports = nextConfig

module.exports = withSentryConfig(
  module.exports,
  { silent: true },
  { hideSourcemaps: true },
)
```

**Comment by harddownloader** [comment]
I deleted the `.next` folder and started the project again, now everything is working.
If someone has a similar problem, just make sure that "experimentalDecorators" and "emitDecoratorMetadata" in tsconfig set as `true`, delete the .next folder, and run the project again.
